<a href="https://colab.research.google.com/github/AdityaKumbhar21/Python_for_Machine_Learning/blob/main/Numpy_Full.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Arrays

Importing Numpy

In [1]:
import numpy as np

Creating a numpy array

In [3]:
a = np.array([1,2,3,4])
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

Creating multidimesional Array

In [5]:
one_dim = np.array([1,2,3,4])
print(one_dim)
one_dim.shape  # describes the shape/dimesion of the array

[1 2 3 4]


(4,)

In [8]:
two_dim = np.array([[1,2,3,4],[5,6,7,8]])
print(two_dim)
two_dim.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

Initial Placeholder value arrays

Null Array

In [10]:
null_array = np.zeros((3,4))
print(null_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


All 1's array

In [12]:
ones_array = np.ones((3,6)) # by default it will create all values with floating point
ones_array = np.ones((3,6), dtype = int)
print(ones_array)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


Creating identity matrix

In [15]:
identity_matrix = np.eye(7, dtype = int)
print(identity_matrix)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


Creating array with random values

In [16]:
random_array = np.random.random((3,4))
print(random_array)

[[0.58586178 0.46888184 0.88545387 0.92923253]
 [0.3573598  0.87138781 0.18581097 0.78527557]
 [0.05670326 0.73342431 0.57141443 0.69952066]]


In [18]:
# creating random integer array within a  range
random_int_array = np.random.randint(1,10, (3,7))
print(random_int_array)

[[1 3 5 3 7 5 5]
 [1 6 7 7 3 5 1]
 [8 2 7 4 2 3 5]]


Creating array with evenly spaced values

In [21]:
evenly_spaced_array = np.linspace(10,30,6,dtype=int) # 6 is the number of elements we want
print(evenly_spaced_array)

[10 14 18 22 26 30]


Array functions

In [24]:
array1 = np.random.randint(1,10, (3,4))

In [26]:
# checking the size of the array
print(array1.size)

# checking the shape of the array
print(array1.shape)

# checking the dimesion of the array
print(array1.ndim)



12
(3, 4)
2


Array operations

In [32]:
array_1 = np.random.randint(1,10, (3,2))
array_2 = np.random.randint(1,10, (3,2))
print(array_1)
print()
print(array_2)

[[1 2]
 [9 9]
 [5 6]]

[[6 6]
 [7 9]
 [5 6]]


In [33]:
print(np.add(array_1, array_2))
print()
print(np.subtract(array_1, array_2))
print()
print(np.multiply(array_1, array_2))
print()
print(np.divide(array_1, array_2))

[[ 7  8]
 [16 18]
 [10 12]]

[[-5 -4]
 [ 2  0]
 [ 0  0]]

[[ 6 12]
 [63 81]
 [25 36]]

[[0.16666667 0.33333333]
 [1.28571429 1.        ]
 [1.         1.        ]]


Array Manipulation

In [34]:
#transpose of an array
transpose_array_1 = array_1.transpose()
print(transpose_array_1)

[[1 9 5]
 [2 9 6]]


In [35]:
# Another method of transpose
transpose_array_1 = array_1.T
print(transpose_array_1)

[[1 9 5]
 [2 9 6]]


In [37]:
# Reshaping the array
reshaped_array = array_1.reshape(3,2)
print(reshaped_array)

[[1 2]
 [9 9]
 [5 6]]
